# Список категорий done
GET http://localhost:3000/api/categories HTTP/1.1

###

# Поиск done
GET http://localhost:3000/api/search?query=Продам HTTP/1.1

###

# Запрашивает все объявления done
GET http://localhost:3000/api/offers HTTP/1.1

###

# Запрашивает объявление с идентификатором :id done

GET http://localhost:3000/api/offers/2 HTTP/1.1

###

# Удаление объявления с идентификатором :id done

DELETE http://localhost:3000/api/offers/19 HTTP/1.1

###

# Добавление нового объявления done

POST http://localhost:3000/api/offers HTTP/1.1
Content-Type: application/json

{
  "categories": ["Журналы"],
  "description": "При покупке с меня бесплатная доставка в черте города. Две страницы заляпаны свежим кофе. Пользовались бережно и только по большим праздникам., Бонусом отдам все аксессуары.",
  "picture": "item16.jpg",
  "title": "Продам новую приставку Sony Playstation 5.",
  "sum": 42698,
  "type": "offer"
}

###

# Обновление объявления done

PUT http://localhost:3000/api/offers/3 HTTP/1.1
Content-Type: application/json

{
  "category": ["Разное", "Игры", "Книги"],
  "description": "Мой дед не мог её сломать. Бонусом отдам все аксессуары. Кому нужен этот новый телефон, если тут такое.",
  "picture": "item06.jpg",
  "title": "Продам книги Стивена Кинга!",
  "sum": 900,
  "type": "buy"
}

###

# Список комментариев done

GET http://localhost:3000/api/offers/3/comments HTTP/1.1

###

# Удаляет комментарий done

DELETE http://localhost:3000/api/offers/3/comments/13 HTTP/1.1

###

# Добавляет новый комментарий к публикации done

POST http://localhost:3000/api/offers/3/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это новый очень хороший комментарий!"
}
